#!/usr/bin/env bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

export DOCKER_HOST=tcp://127.0.0.1:2376
export DOCKER_CERT_PATH="$DIR/tls"
export DOCKER_TLS_VERIFY=1

# DEBUG
#echo "DOCKER_HOST: $DOCKER_HOST"
#echo "DOCKER_CERT_PATH: $DOCKER_CERT_PATH"
#echo "DOCKER_TLS_VERIFY: $DOCKER_TLS_VERIFY"
